-- MySQL Script generated by MySQL Workbench
-- vie 28 ago 2020 10:18:47 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema crustaceocascarudo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema crustaceocascarudo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `crustaceocascarudo` DEFAULT CHARACTER SET utf8 ;
USE `crustaceocascarudo` ;

-- -----------------------------------------------------
-- Table `crustaceocascarudo`.`sexo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `crustaceocascarudo`.`sexo` ;

CREATE TABLE IF NOT EXISTS `crustaceocascarudo`.`sexo` (
  `id_sexo` INT NOT NULL AUTO_INCREMENT,
  `sexo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_sexo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crustaceocascarudo`.`cargo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `crustaceocascarudo`.`cargo` ;

CREATE TABLE IF NOT EXISTS `crustaceocascarudo`.`cargo` (
  `id_cargo` INT NOT NULL AUTO_INCREMENT,
  `cargo` VARCHAR(45) NOT NULL,
  `salario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_cargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crustaceocascarudo`.`empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `crustaceocascarudo`.`empleado` ;

CREATE TABLE IF NOT EXISTS `crustaceocascarudo`.`empleado` (
  `id_empleado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `dui` VARCHAR(10) NOT NULL,
  `nit` VARCHAR(17) NOT NULL,
  `telefono_fijo` VARCHAR(9) NULL,
  `id_cargo` INT NOT NULL,
  `id_sexo` INT NOT NULL,
  PRIMARY KEY (`id_empleado`, `id_cargo`, `id_sexo`),
  INDEX `fk_empleado_sexo_idx` (`id_sexo` ASC),
  INDEX `fk_empleado_cargo1_idx` (`id_cargo` ASC),
  CONSTRAINT `fk_empleado_sexo`
    FOREIGN KEY (`id_sexo`)
    REFERENCES `crustaceocascarudo`.`sexo` (`id_sexo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleado_cargo1`
    FOREIGN KEY (`id_cargo`)
    REFERENCES `crustaceocascarudo`.`cargo` (`id_cargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
