# Generated by Django 3.1 on 2020-10-23 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipo', '0001_initial'),
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id_bodega', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_recurso', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'bodega',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id_mantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
                ('id_empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, to='empleado.empleado')),
                ('id_equipo', models.ForeignKey(db_column='id_equipo', on_delete=django.db.models.deletion.CASCADE, to='equipo.equipo')),
            ],
            options={
                'db_table': 'mantenimiento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoMantenimiento',
            fields=[
                ('id_tipo_mantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_mantenimiento', models.CharField(max_length=45)),
                ('subtipo_mantenimiento', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tipo_mantenimiento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoRecurso',
            fields=[
                ('id_tipo_recurso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_recurso', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tipo_recurso',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MantenimientoPorBodega',
            fields=[
                ('id_mantenimiento_por_bodega', models.AutoField(primary_key=True, serialize=False)),
                ('id_bodega', models.ForeignKey(db_column='id_bodega', on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.bodega')),
                ('id_mantenimiento', models.ForeignKey(db_column='id_mantenimiento', on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.mantenimiento')),
            ],
            options={
                'db_table': 'tipo_mantenimiento_por_recurso',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='id_tipo_mantenimiento',
            field=models.ForeignKey(db_column='id_tipo_mantenimiento', on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.tipomantenimiento'),
        ),
        migrations.AddField(
            model_name='bodega',
            name='id_tipo_recurso',
            field=models.ForeignKey(db_column='id_tipo_recurso', on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.tiporecurso'),
        ),
        migrations.AlterUniqueTogether(
            name='mantenimiento',
            unique_together={('id_empleado', 'id_equipo')},
        ),
    ]
