# Generated by Django 3.1.1 on 2020-09-26 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipo', '0001_initial'),
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id_mantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('id_empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, to='empleado.empleado')),
                ('id_equipo', models.ForeignKey(db_column='id_equipo', on_delete=django.db.models.deletion.CASCADE, to='equipo.equipo')),
            ],
            options={
                'db_table': 'mantenimiento',
                'managed': True,
                'unique_together': {('id_empleado', 'id_equipo')},
            },
        ),
        migrations.CreateModel(
            name='MetodoPreventivo',
            fields=[
                ('id_metodo_preventivo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_metodo_preventivo', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'metodo_preventivo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoCorrectivo',
            fields=[
                ('id_tipo_correctivo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_correctivo', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tipo_correctivo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoPreventivo',
            fields=[
                ('id_tipo_preventivo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_preventivo', models.CharField(max_length=45)),
                ('id_metodo_preventivo', models.ForeignKey(db_column='id_metodo_preventivo', on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.metodopreventivo')),
            ],
            options={
                'db_table': 'tipo_preventivo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Preventivo',
            fields=[
                ('id_preventivo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_preventivo', models.DateField()),
                ('id_mantenimiento', models.ForeignKey(db_column='id_mantenimiento', on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.mantenimiento')),
                ('id_tipo_preventivo', models.ForeignKey(db_column='id_tipo_preventivo', on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.tipopreventivo')),
            ],
            options={
                'db_table': 'preventivo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Innovativo',
            fields=[
                ('id_innovativo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_innovativo', models.DateField()),
                ('id_mantenimiento', models.ForeignKey(db_column='id_mantenimiento', on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.mantenimiento')),
            ],
            options={
                'db_table': 'innovativo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Correctivo',
            fields=[
                ('id_correctivo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_correctivo', models.DateField(blank=True)),
                ('id_mantenimiento', models.ForeignKey(db_column='id_mantenimiento', on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.mantenimiento')),
                ('id_tipo_correctivo', models.ForeignKey(db_column='id_tipo_correctivo', on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.tipocorrectivo')),
            ],
            options={
                'db_table': 'correctivo',
                'managed': True,
                'unique_together': {('id_correctivo', 'id_tipo_correctivo', 'id_mantenimiento')},
            },
        ),
    ]
