# Generated by Django 4.0.2 on 2022-02-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='nombre_recurso',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='descripcion',
            field=models.CharField(max_length=60),
        ),
    ]
