# Generated by Django 3.1 on 2020-10-23 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cargo', models.CharField(max_length=45)),
                ('salario', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'cargo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EstadoEmpleado',
            fields=[
                ('id_estado_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado_empleado', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'estado_empleado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id_sexo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sexo', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'sexo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('fecha_nacimiento', models.DateField()),
                ('dui', models.CharField(max_length=10)),
                ('nit', models.CharField(max_length=17)),
                ('telefono_fijo', models.CharField(blank=True, max_length=9, null=True)),
                ('id_cargo', models.ForeignKey(db_column='id_cargo', on_delete=django.db.models.deletion.CASCADE, to='empleado.cargo')),
                ('id_estado_empleado', models.ForeignKey(db_column='id_estado_empleado', on_delete=django.db.models.deletion.CASCADE, to='empleado.estadoempleado')),
                ('id_sexo', models.ForeignKey(db_column='id_sexo', on_delete=django.db.models.deletion.CASCADE, to='empleado.sexo')),
                ('id_ubicacion', models.ForeignKey(db_column='id_ubicacion', on_delete=django.db.models.deletion.CASCADE, to='equipo.ubicacion')),
            ],
            options={
                'db_table': 'empleado',
                'managed': True,
                'unique_together': {('id_empleado', 'id_cargo', 'id_sexo')},
            },
        ),
    ]
