# Generated by Django 2.2.13 on 2020-08-28 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(max_length=45)),
                ('salario', models.CharField(max_length=45)),
            ],
            options={
                'managed': True,
                'db_table': 'cargo',
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id_sexo', models.AutoField(primary_key=True, serialize=False)),
                ('sexo', models.CharField(max_length=45)),
            ],
            options={
                'managed': True,
                'db_table': 'sexo',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('fecha_nacimiento', models.DateField()),
                ('dui', models.CharField(max_length=10)),
                ('nit', models.CharField(max_length=17)),
                ('telefono_fijo', models.CharField(blank=True, max_length=9, null=True)),
                ('id_cargo', models.ForeignKey(db_column='id_cargo', on_delete=django.db.models.deletion.DO_NOTHING, to='empleado.Cargo')),
                ('id_sexo', models.ForeignKey(db_column='id_sexo', on_delete=django.db.models.deletion.DO_NOTHING, to='empleado.Sexo')),
            ],
            options={
                'unique_together': {('id_empleado', 'id_cargo', 'id_sexo')},
                'managed': True,
                'db_table': 'empleado',
            },
        ),
    ]
