# Generated by Django 3.1.2 on 2020-10-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='id_empleado',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
    ]
