# Generated by Django 2.2.15 on 2020-09-01 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_marca', models.CharField(max_length=45)),
            ],
            options={
                'managed': True,
                'db_table': 'marca',
            },
        ),
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id_tipo_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_equipo', models.CharField(max_length=45)),
            ],
            options={
                'managed': True,
                'db_table': 'tipo_equipo',
            },
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id_edificio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_edificio', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'edificio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id_ubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ubicacion', models.CharField(max_length=45)),
                ('id_edificio', models.ForeignKey(db_column='id_edificio', on_delete=django.db.models.deletion.CASCADE, to='equipo.Edificio')),
            ],
            options={
                'unique_together': {('id_ubicacion', 'id_edificio')},
                'db_table': 'ubicacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EstadoEquipo',
            fields=[
                ('id_estado_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado_equipo', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'estado_equipo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('id_tipo_equipo', models.ForeignKey(db_column='id_tipo_equipo', on_delete=django.db.models.deletion.DO_NOTHING, to='equipo.TipoEquipo')),
            ],
            options={
                'managed': True,
                'db_table': 'equipo',
                'unique_together': {('id_equipo', 'id_tipo_equipo')},
            },
        ),
    ]
