# Generated by Django 3.1 on 2020-09-01 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='id_marca',
            field=models.ForeignKey(db_column='id_marca', on_delete=django.db.models.deletion.DO_NOTHING, to='equipo.marca'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='equipo',
            unique_together={('id_equipo', 'id_tipo_equipo', 'id_marca')},
        ),
    ]
